[package]
name = "cosmic-panel-bin"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cosmic-panel"
path = "src/main.rs"

[dependencies]
smithay = { git = "https://github.com/smithay/smithay", default-features = false, features = ["use_system_lib", "desktop", "backend_egl", "backend_drm", "renderer_gl", "slog-stdlog"], rev = "2de946cf9e1fcd264c7896831f1934243806d3db"}
# smithay = { path = "../../smithay", default-features = false, features = ["use_system_lib", "desktop", "backend_egl", "backend_drm", "renderer_gl", "slog-stdlog"] }
sctk = { git = "https://github.com/smithay/client-toolkit", package = "smithay-client-toolkit", rev = "638ca60e3ae8277d645991cc986be3df5981fbb6", features = ["calloop", "xkbcommon"] }
# xdg-shell-wrapper = { path = "../../xdg-shell-wrapper" }
# xdg-shell-wrapper-config = { path = "../../xdg-shell-wrapper/xdg-shell-wrapper-config" }
xdg-shell-wrapper = { git = "https://github.com/pop-os/xdg-shell-wrapper", branch = "space-refactor" }
xdg-shell-wrapper-config = { git = "https://github.com/pop-os/xdg-shell-wrapper", branch = "space-refactor" }

launch-pad = { git = "https://github.com/pop-os/launch-pad.git", branch = "on-exit-before-restart" }
# launch-pad = { path = "../../launch-pad" }
cosmic-panel-config = { path = "../cosmic-panel-config" }
wayland-egl = { version = "=0.30.0-beta.13" }
wayland-protocols-wlr = { version = "=0.1.0-beta.13", features = ["client"] }
cosmic-theme = { git = "https://github.com/pop-os/cosmic-theme.git" }

anyhow = "1.0.63"
shlex = "1.1.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_warn"] }
slog-term = "2.9.0"
slog-async = "2.7.0"
slog-stdlog = "4.1.1"
slog-scope = "4.4.0"
libc = "0.2.132"
freedesktop-desktop-entry = "0.5.0"
xdg = "2.4.1"
itertools = "0.10.3"
notify = "5.0"
tokio = { version = "1", features = ["process", "sync", "rt", "rt-multi-thread", "macros", "io-util", "time"] }
csscolorparser = "0.6.2"
