[package]
name = "cosmic-panel-bin"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cosmic-panel"
path = "src/main.rs"

[dependencies]
smithay = { git = "https://github.com/smithay/smithay", default-features = false, features = ["use_system_lib", "desktop", "backend_egl", "backend_drm", "renderer_gl"], rev = "0a288b1"}
sctk = { git = "https://github.com/pop-os/client-toolkit", package = "smithay-client-toolkit", features = ["calloop", "xkbcommon"], rev = "6cd6095" }
xdg-shell-wrapper = { git = "https://github.com/pop-os/xdg-shell-wrapper", rev = "5dce1cf" }
xdg-shell-wrapper-config = { git = "https://github.com/pop-os/xdg-shell-wrapper", rev = "5dce1cf" }
# xdg-shell-wrapper = { path = "../../xdg-shell-wrapper" }
# xdg-shell-wrapper-config = { path = "../../xdg-shell-wrapper/xdg-shell-wrapper-config" }
# smithay = { path = "../../smithay", default-features = false, features = ["use_system_lib", "desktop", "backend_egl", "backend_drm", "renderer_gl"] }
# sctk = { package = "smithay-client-toolkit", path = "../../fork/client-toolkit", default-features = false, features = ["calloop", "xkbcommon"] }
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.16", features = ["fmt", "env-filter", "ansi"]}
tracing-journald = "0.3.0"
tracing-futures = "0.2.5"
launch-pad = { git = "https://github.com/pop-os/launch-pad.git" }
# launch-pad = { path = "../../launch-pad" }
cosmic-panel-config = { path = "../cosmic-panel-config" }
wayland-egl = "0.30.0"
wayland-protocols-wlr = { version = "0.1.0", features = ["client"] }
cosmic-theme = { git = "https://github.com/pop-os/cosmic-theme.git" }
transpose = "0.2.2"
anyhow = "1.0.63"
shlex = "1.1.0"
log-panics = { version = "2", features = ["with-backtrace"] }
libc = "0.2.132"
freedesktop-desktop-entry = "0.5.0"
xdg = "2.4.1"
itertools = "0.10.3"
notify = "5.0"
tokio = { version = "1", features = ["process", "sync", "rt", "rt-multi-thread", "macros", "io-util", "time"] }
csscolorparser = "0.6.2"
image = "0.24"
cosmic-config = { git = "https://github.com/pop-os/libcosmic" }
zbus = "3.11"
rand = "0.8" 
